services:
  # Backend
  portfolio-backend:
    container_name: portfolio-backend
    build: 
      context: .
      dockerfile: ./Python/Dockerfile
    volumes:
      - "./Project/My-Portfolio-Back:/mysite"
    ports:
      - "8000:8000"
    tty: true
    working_dir: "/mysite"
    networks:
      - portfolio-networks

  # # データベース
  # portfolio-db:
  #   container_name: portfolio-db
  #   networks:
  #     - portfolio-networks

  # # Frontend
  # portfolio-frontend:
  #   container_name: portfolio-frontend
  #   networks:
  #     - portfolio-networks

networks:
  portfolio-networks:
    driver: bridge
