services:
  # # Backend
  # portfolio-backend:
  #   container_name: portfolio-backend
  #   networks:
  #     - portfolio-networks

  # # データベース
  # portfolio-db:
  #   container_name: portfolio-db
  #   networks:
  #     - portfolio-networks

  # Frontend
  portfolio-frontend:
    container_name: portfolio-frontend
    build: 
      context: .
      dockerfile: ./Node/Dockerfile
    volumes:
      - "./Project/My-Portfolio-Front:/home/node/app"
    ports:
      - "3000:3000"
    tty: true
    networks:
      - portfolio-networks

networks:
  portfolio-networks:
    driver: bridge
